<a href="https://colab.research.google.com/github/Pabalelo96/CreditCardFraudDetection/blob/main/CardFraudDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("/creditcard.csv")

In [29]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [30]:
df.shape

(27819, 31)

In [31]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27819 entries, 0 to 27818
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    27819 non-null  int64
 1   V1      27818 non-null  float64
 2   V2      27818 non-null  float64
 3   V3      27818 non-null  float64
 4   V4      27818 non-null  float64
 5   V5      27818 non-null  float64
 6   V6      27818 non-null  float64
 7   V7      27818 non-null  float64
 8   V8      27818 non-null  float64
 9   V9      27818 non-null  float64
 10  V10     27818 non-null  float64
 11  V11     27818 non-null  float64
 12  V12     27818 non-null  float64
 13  V13     27818 non-null  float64
 14  V14     27818 non-null  float64
 15  V15     27818 non-null  float64
 16  V16     27818 non-null  float64
 17  V17     27818 non-null  float64
 18  V18     27818 non-null  float64
 19  V19     27818 non-null  float64
 20  V20     27818 non-null  float64
 21  V21     27818 non-null  float64
 22  V22     27818 non-null  float64
 23  V23     27818 non-null  float64
 24  V24     27818 non-null  float64
 25  V25     27818 non-null  float64
 26  V26     27818 non-null  float64
 27  V27     27818 non-null  float64
 28  V28     27818 non-null  float64
 29  Amount  27818 non-null  float64
 30  Class   27818 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.6 MB

In [33]:
df.isnull()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27814,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27815,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27816,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27817,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27818,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [34]:
df.isnull().sum()

Time      0
V1        1
V2        1
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [35]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
27814    False
27815    False
27816    False
27817    False
27818    False
Length: 27819, dtype: bool

In [36]:
df.duplicated().sum()

np.int64(111)

In [37]:
df["Class"].value_counts()

Class
0.0    27725
1.0       93
Name: count, dtype: int64

In [38]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [39]:
df.duplicated().sum()

np.int64(111)

In [40]:
df.drop_duplicates()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27814,34711,1.443955,-1.052462,-0.141721,-1.564017,-0.966274,-0.333886,-0.777060,0.023616,-2.168826,...,-0.479940,-1.165220,0.155226,-0.409701,0.179672,-0.446258,0.004329,0.000060,32.39,0.0
27815,34711,-0.263364,0.931818,1.193111,-0.507924,0.862019,0.249381,0.815449,-0.090801,-0.520583,...,-0.310112,-0.648621,-0.253746,-1.030111,-0.046091,0.107328,0.101296,-0.124600,1.49,0.0
27816,34712,0.976345,-1.024867,0.978714,0.639442,-1.413711,0.311635,-0.909035,0.232423,-0.493025,...,-0.279978,-0.599463,-0.081403,-0.059427,0.202311,-0.405753,0.055109,0.052975,151.00,0.0
27817,34712,1.464604,-0.437919,-0.018869,-1.057177,-0.154243,0.251215,-0.584866,-0.025483,-0.841369,...,-0.148384,-0.454571,-0.019732,-1.313689,0.379650,-0.368497,0.031746,0.007238,8.00,0.0
27818,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.drop_duplicates(inplace=True)

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27708 entries, 0 to 27818
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    27708 non-null  int64
 1   V1      27707 non-null  float64
 2   V2      27707 non-null  float64
 3   V3      27707 non-null  float64
 4   V4      27707 non-null  float64
 5   V5      27707 non-null  float64
 6   V6      27707 non-null  float64
 7   V7      27707 non-null  float64
 8   V8      27707 non-null  float64
 9   V9      27707 non-null  float64
 10  V10     27707 non-null  float64
 11  V11     27707 non-null  float64
 12  V12     27707 non-null  float64
 13  V13     27707 non-null  float64
 14  V14     27707 non-null  float64
 15  V15     27707 non-null  float64
 16  V16     27707 non-null  float64
 17  V17     27707 non-null  float64
 18  V18     27707 non-null  float64
 19  V19     27707 non-null  float64
 20  V20     27707 non-null  float64
 21  V21     27707 non-null  float64
 22  V22     27707 non-null  float64
 23  V23     27707 non-null  float64
 24  V24     27707 non-null  float64
 25  V25     27707 non-null  float64
 26  V26     27707 non-null  float64
 27  V27     27707 non-null  float64
 28  V28     27707 non-null  float64
 29  Amount  27707 non-null  float64
 30  Class   27707 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.8 MB

In [44]:
df['Amount'].min()

0.0

In [45]:
df['Time'].min()

0

In [46]:
df['Class'].value_counts()

Class
0.0    27614
1.0       93
Name: count, dtype: int64

In [47]:
df['Class'].unique()

array([ 0.,  1., nan])

##EDA

##Univariate

In [48]:
df["Amount"].describe()
# df["Time"].describe()

count    27707.00000
mean        77.47077
std        219.99108
min          0.00000
25%          6.47000
50%         19.95000
75%         69.81500
max       7879.42000
Name: Amount, dtype: float64

##Bi Varient

#Multi Varient

In [54]:
df.corr(numeric_only=True)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
Time,1.000000,0.016746,-0.084719,-0.074604,-0.026714,-0.077840,-0.032753,-0.021262,0.044694,-0.294747,...,0.024982,0.044043,-0.010333,-0.014416,0.055475,-0.040316,-0.000535,0.001792,0.056793,-0.007865
V1,0.016746,1.000000,-0.192097,0.346657,-0.115179,0.128666,0.118990,0.219681,-0.146362,-0.021280,...,-0.097941,0.026198,-0.040550,-0.003312,0.167894,0.025872,-0.143410,0.138281,-0.211869,-0.247258
V2,-0.084719,-0.192097,1.000000,-0.307414,0.130559,-0.180238,-0.025068,-0.084904,0.080022,-0.043109,...,0.026798,-0.112962,-0.002678,-0.026206,-0.089619,-0.059912,0.082829,0.025850,-0.481033,0.224745
V3,-0.074604,0.346657,-0.307414,1.000000,-0.172059,0.346776,0.026953,0.396358,-0.338991,0.179260,...,-0.017980,0.244679,0.055195,0.037016,-0.189315,0.066227,-0.185152,0.039615,-0.154409,-0.436442
V4,-0.026714,-0.115179,0.130559,-0.172059,1.000000,-0.093078,-0.047291,-0.135802,0.109922,-0.060506,...,0.005545,-0.019523,-0.013227,-0.022687,-0.020141,0.037957,0.061005,-0.018495,0.107331,0.238037
V5,-0.077840,0.128666,-0.180238,0.346776,-0.093078,1.000000,0.098321,0.103478,-0.158482,0.042602,...,-0.049896,-0.070184,0.027438,-0.005025,-0.068461,-0.048674,-0.134710,-0.000485,-0.364727,-0.224933
V6,-0.032753,0.118990,-0.025068,0.026953,-0.047291,0.098321,1.000000,0.117252,-0.086458,0.051755,...,0.039939,0.016545,-0.005269,0.021992,0.060784,0.012435,-0.021589,-0.029422,0.217499,-0.108187
V7,-0.021262,0.219681,-0.084904,0.396358,-0.135802,0.103478,0.117252,1.000000,-0.156386,0.057287,...,-0.104950,0.028189,0.060540,0.006983,-0.127073,-0.041051,-0.145373,-0.106935,0.318761,-0.348486
V8,0.044694,-0.146362,0.080022,-0.338991,0.109922,-0.158482,-0.086458,-0.156386,1.000000,-0.075358,...,-0.140439,0.048258,-0.080794,0.010162,0.044462,-0.009455,0.085753,0.042486,-0.061757,0.181445
V9,-0.294747,-0.021280,-0.043109,0.179260,-0.060506,0.042602,0.051755,0.057287,-0.075358,1.000000,...,-0.031828,0.007811,-0.029598,0.004337,0.100885,0.069676,-0.056673,-0.080564,-0.013496,-0.152316
V10,0.096154,0.043391,-0.026733,0.229130,-0.098394,0.172622,0.059017,0.215618,-0.158638,-0.028297,...,0.001928,-0.030877,0.018109,0.012183,-0.015864,0.010365,-0.132887,-0.091959,-0.109663,-0.334275
V11,-0.161643,-0.049043,0.112141,-0.150241,0.065570,-0.069992,-0.100808,-0.141681,0.027549,0.099961,...,0.019389,0.038525,0.029806,0.016029,-0.095502,0.035154,0.044447,0.004799,-0.030284,0.260388
V12,0.317924,0.069675,-0.128351,0.142204,-0.123460,0.053696,0.003009,0.194866,-0.083874,-0.271220,...,0.049231,0.076445,-0.016271,0.026393,0.015076,-0.016790,-0.033791,0.003717,0.045265,-0.304456
V13,-0.299379,0.012104,0.050257,0.001778,0.053502,0.043948,0.022307,-0.021880,-0.012360,0.268296,...,-0.031377,-0.049814,-0.008364,-0.004218,0.037941,0.033038,-0.006395,-0.006778,-0.013833,-0.003039
V14,-0.225846,0.168910,-0.113614,0.269281,-0.091573,0.103731,0.090909,0.114829,-0.075432,0.287850,...,-0.039315,-0.076139,0.041322,0.041163,-0.054581,0.030545,-0.094925,0.047958,-0.015908,-0.414150
V15,0.150756,0.049690,0.052648,-0.165062,-0.118853,0.072482,-0.112179,0.074711,-0.011340,-0.220557,...,0.022867,0.016025,0.011209,-0.009050,-0.097288,-0.055937,0.009543,-0.033827,-0.039923,-0.009359
V16,0.033703,0.143784,-0.069946,0.053939,-0.168339,0.135021,0.024680,0.150077,-0.056498,-0.064675,...,-0.028564,-0.024191,0.000433,-0.003178,0.081967,0.056644,-0.080324,-0.033843,-0.017157,-0.298118
V17,-0.090735,0.121389,-0.096517,0.198332,-0.003521,0.075799,0.038661,0.172084,-0.092682,0.244894,...,-0.039151,0.016103,0.051818,-0.004693,-0.071242,-0.068724,-0.112532,-0.054836,0.005717,-0.409290
V18,-0.050154,0.001624,-0.011636,0.051924,-0.030325,0.099533,0.055486,0.107644,-0.038055,0.121372,...,-0.036759,-0.084157,-0.006373,-0.009622,0.021631,0.035307,-0.043410,-0.013828,0.036349,-0.179922
V19,0.026145,0.017592,-0.016778,-0.035130,-0.027980,-0.004796,0.095431,-0.047471,0.021059,-0.055855,...,0.022334,0.008838,-0.029435,-0.003420,-0.019477,-0.033902,0.016655,-0.012598,-0.035583,0.024253
V20,0.016410,-0.134361,-0.069849,-0.110155,0.027220,0.006415,-0.022963,-0.032923,0.047079,0.012963,...,-0.147965,0.047142,0.027346,-0.020499,-0.001234,0.012756,-0.025624,0.116959,0.333670,0.057797
V21,0.024982,-0.097941,0.026798,-0.017980,0.005545,-0.049896,0.039939,-0.104950,-0.140439,-0.031828,...,1.000000,-0.176669,0.064688,-0.005001,0.024545,-0.012685,0.033772,0.058201,0.084610,0.042863
V22,0.044043,0.026198,-0.112962,0.244679,-0.019523,-0.070184,0.016545,0.028189,0.048258,0.007811,...,-0.176669,1.000000,-0.004670,0.009731,-0.039741,-0.064467,-0.050881,-0.012510,-0.038748,-0.022321
V23,-0.010333,-0.040550,-0.002678,0.055195,-0.013227,0.027438,-0.005269,0.060540,-0.080794,-0.029598,...,0.064688,-0.004670,1.000000,0.017874,0.056841,0.027805,-0.070376,0.100332,-0.132752,-0.031906
V24,-0.014416,-0.003312,-0.026206,0.037016,-0.022687,-0.005025,0.021992,0.006983,0.010162,0.004337,...,-0.005001,0.009731,0.017874,1.000000,-0.027819,-0.014073,0.012099,0.009422,0.013617,-0.026617
V25,0.055475,0.167894,-0.089619,-0.189315,-0.020141,-0.068461,0.060784,-0.127073,0.044462,0.100885,...,0.024545,-0.039741,0.056841,-0.027819,1.000000,-0.123019,0.046366,0.051345,-0.039981,0.030614
V26,-0.040316,0.025872,-0.059912,0.066227,0.037957,-0.048674,0.012435,-0.041051,-0.009455,0.069676,...,-0.012685,-0.064467,0.027805,-0.014073,-0.123019,1.000000,-0.013692,0.025668,0.031361,0.017529
V27,-0.000535,-0.143410,0.082829,-0.185152,0.061005,-0.134710,-0.021589,-0.145373,0.085753,-0.056673,...,0.033772,-0.050881,-0.070376,0.012099,0.046366,-0.013692,1.000000,0.065987,0.047488,0.122397
V28,0.001792,0.138281,0.025850,0.039615,-0.018495,-0.000485,-0.029422,-0.106935,0.042486,-0.080564,...,0.058201,-0.012510,0.100332,0.009422,0.051345,0.025668,0.065987,1.000000,-0.024163,0.020041
Amount,0.056793,-0.211869,-0.481033,-0.154409,0.107331,-0.364727,0.217499,0.318761,-0.061757,-0.013496,...,0.084610,-0.038748,-0.132752,0.013617,-0.039981,0.031361,0.047488,-0.024163,1.000000,0.005049
Class,-0.007865,-0.247258,0.224745,-0.436442,0.238037,-0.224933,-0.108187,-0.348486,0.181445,-0.152316,...,0.042863,-0.022321,-0.031906,-0.026617,0.030614,0.017529,0.122397,0.020041,0.005049,1.000000

In [55]:
df["Amount"].describe()

count    27707.00000
mean        77.47077
std        219.99108
min          0.00000
25%          6.47000
50%         19.95000
75%         69.81500
max       7879.42000
Name: Amount, dtype: float64